[MVS-446] Create submit vaccination endpoint
david-fraley/MassVaccinationSystem pull request #137
Opened 2020-12-30 22:11 UTC by axn9t9

## :floppy_disk: [Code Check]
_Make sure you've checked/done the following before making this PR!_
* Does your code build/run?
* Does your design approach make sense?
* Does your work achieve the intention of the card?
* Does your code have any unintentional side effects -- have you tested a full workflow & checked the logic branches you touched?
* Did you make a unit test for your code (as appropriate)?
* Is your branch relatively up to date with the Development branch (within ~2 commits)
* Have you moved the card to "Needs QA" in Jira

## :flipper: [JIRA Sprint Card]

https://mass-immunization-system.atlassian.net/browse/MVS-446

## :newspaper: [Work Description]

## :vertical_traffic_light: [Testing/QA Notes]

- Run docker containers
- Create preliminary FHIR resources (referenced FHIR resources must exist)
- Send a POST request to /submit-vaccination with the request data found in models/Immunization and models/Observation

> {
>   "Immunization": {},
>   "Observation": {}
> }

- Ensure the response data contains all of the provided information.

2020-12-30 23:41 UTC, rrucker3 requested changes
I wasn't able to get a successful test. First, I copied the objects from Immunization.js and Observation.js, but I got this error: "Can not create resource with ID[3303], no resource with this ID exists and clients may only assign IDs which contain at least one non-numeric character"

Then I tried removing the reaction element from the Immunization object, but that failed too, with this error: imm.reaction is not iterable.

I put reaction back in as [""], but then I got this error: "Can not create resource with ID[715], no resource with this ID exists and clients may only assign IDs which contain at least one non-numeric character"

Bottom line, I think the testing instructions need to be more detailed. I can't just take the models from the models files and have them work.

2020-12-30 23:41 UTC, rrucker3 commented on broker/server.js
> +          response.Observation = obs_res;
Can you also get the reaction field of the Immunization to point to the newly created Observation? You can use a https://www.hl7.org/fhir/http.html#patch request to update a specific field in an existing resource.

2021-01-04 03:29 UTC, TomMakes commented
I'm not seeing any places where you ensure the response data contains all the necessary info.

2021-01-04 22:10 UTC, rrucker3 approved these changes

2021-01-04 22:15 UTC, merged