[MVS-539] connect the “download” button to a pdf file generator in the single patient follow up page
david-fraley/MassVaccinationSystem pull request #146
Opened 2021-01-08 18:44 UTC by ShahdSawalhi

## :floppy_disk: [Code Check]
_Make sure you've checked/done the following before making this PR!_
* Does your code build/run?
* Does your design approach make sense?
* Does your work achieve the intention of the card?
* Does your code have any unintentional side effects -- have you tested a full workflow & checked the logic branches you touched?
* Did you make a unit test for your code (as appropriate)?
* Is your branch relatively up to date with the Development branch (within ~2 commits)
* Have you moved the card to "Needs QA" in Jira

## :flipper: [JIRA Sprint Card]

https://mass-immunization-system.atlassian.net/browse/MVS-539

## :newspaper: [Work Description]

In the single patient follow up page, there should be an option to download the generated qr code. When the "Download" button is clicked, a pdf file is generated and can be saved/ printed. 
The pdf file should contain a title "COVID-19 Vaccination Registration", a short description of what the QR code will be used for, the registered name and the QR code underneath. 

## :vertical_traffic_light: [Testing/QA Notes]

- Run "yarn install" because a new dependency is used in this branch 
- Run and compile the Patient Registration app 
- Go through the Single Patient Registration work flow 
- When reaching the follow up/ QR code page click the "Download As PDF" Button 
- A pdf file should pop up with the formatting mentioned above 
- Make sure you can view the qr code on the pdf file

2021-01-09 15:52 UTC, TomMakes requested changes
Ran the application in Firefox, fetched the QR code easily with my phone.

Approved once you resolve the two minor things I mentioned.

2021-01-09 15:52 UTC, TomMakes commented on PatientRegistrationApp/src/components/SinglePatientFollowUp.vue
> +        </v-radio-group>
Can you bind a variable to this selection so that the choice is stored somewhere?

2021-01-09 15:52 UTC, TomMakes commented on PatientRegistrationApp/src/components/SinglePatientFollowUp.vue
> +</v-row>
Adjust row tabbing to align with above row.

2021-01-10 01:08 UTC, TomMakes approved these changes

2021-01-10 16:19 UTC, grohde1015 commented
Looks good on my end! Ran in both Chrome and Internet Explorer. Just a note that should be considered is the naming convention of the pdf itself. This is beyond the scope of this PR, but having a set naming convention may be easier for the user to identify in their downloads.

2021-01-10 16:20 UTC, grohde1015 approved these changes

2021-01-10 17:43 UTC, david-fraley requested changes
Where do we specify the filename of the pdf generated? Wherever that occurs, let's change it to "COVID-19_Registration_QR_Code"

2021-01-10 18:33 UTC, david-fraley approved these changes

2021-01-10 18:41 UTC, merged