Mvs 546 call to healthcheck in pat reg
david-fraley/MassVaccinationSystem pull request #165
Opened 2021-01-22 01:26 UTC by adelk719

## :floppy_disk: [Code Check]
_Make sure you've checked/done the following before making this PR!_
* Does your code build/run?
* Does your design approach make sense?
* Does your work achieve the intention of the card?
* Does your code have any unintentional side effects -- have you tested a full workflow & checked the logic branches you touched?
* Did you make a unit test for your code (as appropriate)?
* Is your branch relatively up to date with the Development branch (within ~2 commits)
* Have you moved the card to "Needs QA" in Jira

## :flipper: [JIRA Sprint Card]

https://mass-immunization-system.atlassian.net/browse/MVS-546

## :newspaper: [Work Description]

Added healthcheck functionality to patient registration app is that Success! is returned when patient info is submitted.

## :vertical_traffic_light: [Testing/QA Notes]

Follow the setup directions for the PatReg app in the readme.
Check if clicking "Yes," when submitting should return "Success!" in the web console

2021-01-22 22:09 UTC, axn9t9 requested changes

2021-01-22 22:09 UTC, axn9t9 commented on PatientRegistrationApp/src/App.vue
> +									<v-card flat><SinglePatientReviewSubmit ref="singlepatientreviewsubmit"/></v-card>
May you follow camelCase for the ref here and for HouseholdReviewSubmit (and update the references)?

2021-01-22 22:17 UTC, axn9t9 reviewed
Looks good. Just a few nitpicks. Good work!

2021-01-23 19:28 UTC, rrucker3 commented
That sure is a lot of stuff to commit. Could you rebase on the current Development branch and remove the generated code? https://github.com/david-fraley/MassVaccinationSystem/pull/167 made it so that the generated code isn't pulled into the PR.

![image](https://user-images.githubusercontent.com/5760169/105612043-c9553880-5d7e-11eb-9826-e348b7089827.png)

2021-01-23 20:28 UTC, axn9t9 commented
> That sure is a lot of stuff to commit. Could you rebase on the current Development branch and remove the generated code? #167 made it so that the generated code isn't pulled into the PR.
> 
> ![image](https://user-images.githubusercontent.com/5760169/105612043-c9553880-5d7e-11eb-9826-e348b7089827.png)

I would make a commit deleting the directories first, then rebase. If you rebase first, deleting the directories wont be tracked. Ran into this issue earlier.

2021-01-29 02:08 UTC, axn9t9 approved these changes

2021-02-02 04:07 UTC, merged