MVS-708: remove the status=booked restriction to allow multiple doses
david-fraley/MassVaccinationSystem pull request #207
Opened 2021-03-03 23:26 UTC by benjf

## :floppy_disk: [Code Check]
_Make sure you've checked/done the following before making this PR!_
* Does your code build/run?
* Does your design approach make sense?
* Does your work achieve the intention of the card?
* Does your code have any unintentional side effects -- have you tested a full workflow & checked the logic branches you touched?
* Did you make a unit test for your code (as appropriate)?
* Is your branch relatively up to date with the Development branch (within ~2 commits)
* Have you moved the card to "Needs QA" in Jira

## :flipper: [JIRA Sprint Card]

https://mass-immunization-system.atlassian.net/browse/MVS-708

## :newspaper: [Work Description]

This was a very simple change - I just removed the status=booked restriction when looking up an Appointment. Everything else looks to work as expected.

## :vertical_traffic_light: [Testing/QA Notes]

I checked in for a 2nd and then a 3rd visit.

2021-03-03 23:39 UTC, thespaniard514 submitted a review, later dismissed

2021-03-07 21:01 UTC, TomMakes requested changes

2021-03-07 21:01 UTC, TomMakes commented on PointOfDispensingApp/src/store/store.js
> +                    state.screeningResponses.vaccinationDecision = 'No'
Add extra check to see if there is an existing state.immunizationResource before trying to access an attribute of it.

Wrap these checks to ensure state.immunizationResource exists.
if(state.immunizationResource) {
}

2021-03-07 21:01 UTC, TomMakes commented on PointOfDispensingApp/src/store/store.js
> +                let numberOfDoses = payload.Immunization.length
Even though it's not required, it's good practice to end lines (where applicable) with a ' ; ' to clarify an end of operations.

2021-03-07 21:01 UTC, TomMakes commented on PointOfDispensingApp/src/store/store.js
> +            console.log(payload)
Remove console log before merging. This keeps the log tidy for others.

In general, only error messages should be kept to display in the log.

2021-03-15 16:58 UTC, thespaniard514 approved these changes

2021-03-18 12:44 UTC, TomMakes approved these changes

2021-03-23 03:31 UTC, thespaniard514 approved these changes

2021-03-23 03:35 UTC, merged