Mvs 210  standardize vue page height
david-fraley/MassVaccinationSystem pull request #49
Opened 2020-11-02 17:22 UTC by dmcook5208

## :flipper: [JIRA Sprint Card]
https://mass-immunization-system.atlassian.net/browse/MVS-210

## :newspaper: [Work Description]
Updated App.vue to utilize 100% of the display height

## :vertical_traffic_light: [Testing/QA Notes]
- complete the single patient workflow and verify that the navigation buttons along the button (next, previous, submit) are displayed and function as expected.
- complete the household workflow and verify that the navigation buttons along the button (next, previous, submit) are displayed and function as expected.
- verify that the navigation buttons stay at the bottom of the screen as you resize the browser window

2020-11-03 04:02 UTC, david-fraley requested changes

2020-11-04 19:43 UTC, dmcook5208 commented on PatientRegistrationApp/src/App.vue
> +									<!--listen for changes in the button selections-->
That's fine!  Deleted the comment

2020-11-04 19:43 UTC, dmcook5208 commented on PatientRegistrationApp/src/App.vue
> +						<!-- v-stepper-header is the progress bar along the top of the page -->
That's fine!  Deleted the comment

2020-11-05 02:39 UTC, david-fraley approved these changes
Looks good thanks!

2020-11-05 16:57 UTC, merged